#!/usr/bin/env bash


rm -rf kaamelott-soundboard
git clone --depth 1 https://github.com/2ec0b4/kaamelott-soundboard.git
pushd kaamelott-soundboard/sounds
for mp3_file in *.mp3
do
    ffmpeg -i ${mp3_file} ../../sounds/${mp3_file/.mp3/.wav}
done
popd

cp kaamelott-soundboard/sounds/sounds.json sounds/
sed -i s/\.mp3/\.wav/g sounds/sounds.json
rm -rf kaamelott-soundboard